---
- name: Bootstrap Main Node
  hosts: main
  become: yes
    
  tasks: 
  - name: download apt key
    ansible.builtin.apt_key: 
      url: https://packages.grafana.com/gpg.key
      state: present
  
  - name: Add grafana repo to sources.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana
      state: present
      
  - name: Update apt cache and install Grafana
    ansible.builtin.apt:
      name: grafana
      update_cache: yes
      
  - name: Ensure Grafana is started and enabled
    ansible.builtin.systemd_service:
      name: grafana-server
      enabled: true
      state: started
      